### ISSUE TITLE
Página del Admin

### ISSUE THREAD

**Issue by marcos-do** [ucudal/pii_2019_equipo8#18]
Crear la página del Admin con todo lo que debería mostrar (Consultas, Workers, Contratos, Usuarios deshabilitados)

**Comment by fmachadopiriz** [comment]
Vean https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions y https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines
